In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing,cross_decomposition,model_selection,metrics
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
%matplotlib inline
import dateutil
from tqdm import tqdm
from sklearn import linear_model
import datetime
import numpy as np
import pandas as pd

import plotly.graph_objects as go
from ipywidgets import widgets
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels import tsa
import numpy as np
import pandas as pd

import plotly.graph_objects as go
from ipywidgets import widgets

In [3]:
confirmedGlobal=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',encoding='utf-8',na_values=None)
confirmedGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,8/27/20
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,37599,37599,37856,37894,37953,37999,38054,38070,38113,38129
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,7654,7812,7967,8119,8275,8427,8605,8759,8927,9083
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,39444,39847,40258,40667,41068,41460,41858,42228,42619,43016
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,1005,1024,1024,1045,1045,1045,1060,1060,1098,1098
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1966,2015,2044,2068,2134,2171,2222,2283,2332,2415
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,93,94,94,94,94,94,94,94,94,94
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,305966,312659,320884,329043,336802,342154,350867,359638,370188,380292
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,41846,42056,42319,42477,42616,42792,42825,42936,43067,43270
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,113,113,113,113,113,113,113,113,113,113
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,3,4,...,3966,3971,3972,3981,3985,3988,3991,3997,4006,4019
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,33,33,33,33,33,33,33,33,33,33
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1092,1093,1094,1103,1105,1106,1106,1107,1110,1113
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,462,462,462,462,462,463,463,463,463,463
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,230
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,1,1,...,17446,17683,17852,18029,18231,18330,18464,18608,18714,18822
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,647,651,651,651,652,652,653,653,653,655
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,23829,24084,24431,24762,25062,25253,25495,25706,26033,26361
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,34474,34620,34759,34921,35105,35274,35426,35559,35707,35844
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,1424,1531,1610,1703,1703,1765,1765,1765,1765,1765
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,47581,47950,48303,48661,49038,49330,49719,50076,50393,50756
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,282344,285091,287959,290360,292625,294598,297083,299628,302147,304583
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,153,155,156,157,158,161,161,164,165,165
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,69673,69801,69950,70111,70285,70468,70645,70727,70974,71165
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,78897,79479,80178,80894,81468,81936,82092,82447,83030,83500
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,475,553,605,648,668,686,713,730,760,818
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,2063,2095,2095,2095,2115,2115,2115,2115,2145,2145
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,147,147,153,154,155,155,156,173,173,184
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,103019,105050,106065,107435,108427,109149,110148,110999,112094,113129
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,16351,16691,17029,17396,17715,17715,18029,18326,18609,18920
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,1308,1308,1308,1308,1308,1308,1562,1562,1562,1562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,NaN,Thailand,15.870032,100.992541,2,3,5,7,8,8,...,3382,3382,3389,3390,3390,3395,3402,3402,3404,3410
237,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,25,25,25,25,26,26,26,26,26,27
238,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,1173,1190,1212,1239,1275,1277,1295,1309,1326,1326
239,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,629,686,767,864,930,1007,1099,1252,1411,1429
240,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,2314,2427,2543,2607,2738,2818,2893,3069,3206,3323
241,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,251805,253108,254520,255723,257032,258249,259692,261194,262507,263998
242,NaN,US,40.000000,-100.000000,1,1,2,2,5,5,...,5483388,5529824,5573847,5622470,5667070,5701645,5739536,5777710,5821819,5867785
243,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1603,1656,1750,1848,2166,2263,2362,2426,2524,2679
244,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,96653,98658,100810,102948,105337,107379,109234,110949,112653,114663
245,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,64906,65341,65802,66193,66617,67007,67282,67621,68020,68511
246,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
247,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,166,166,166,167,167,167,168,168,168,168
248,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,11,11,11,21,21,21,21,26,26,26
249,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,203,205,205,205,205,205,205,205,205,205
250,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,609,613,613,614,614,614,616,620,623,623
251,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
252,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,222,223,229,231,239,246,248,256,270,272
253,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,336,336,336,336,336,336,336,336,336,336
254,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
255,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,315,327,334,347,383,383,383,383,464,482
256,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,320286,321098,322280,323313,324601,325642,326614,327798,328846,330368
257,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1485,1493,1506,1516,1521,1527,1533,1536,1543,1551
258,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,36352,37112,37547,38074,38532,38946,39348,39641,39964,40447
259,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,35697,36868,37567,38219,38957,39564,40338,41158,41965,42898
260,NaN,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,989,994,1007,1009,1014,1016,1022,1029,1034,1036
261,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,17306,17606,17989,18313,18476,18802,19213,19678,20155,20677
262,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,10,10,10,10,10,10,10,10,10,10
263,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1889,1892,1899,1906,1907,1911,1916,1924,1930,1933
264,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,9981,10218,10372,10627,10831,11082,11148,11285,11376,11601
265,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5378,5643,5745,5815,5893,5930,6070,6196,6251,6292

In [4]:
deathGLobal=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
deathGLobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,8/27/20
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,1375,1375,1385,1385,1385,1387,1389,1397,1401,1401
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,232,234,238,240,245,250,254,259,263,266
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,1391,1402,1411,1418,1424,1435,1446,1456,1465,1475
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,53,53,53,53,53,53,53,53,53,53
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,90,92,93,94,94,96,100,102,103,105
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,6048,6330,6517,6730,6848,6985,7366,7563,7839,8050
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,832,833,836,842,850,852,854,858,861,864
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,52,52,52,52,52,52,52,52,52,52
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,6,6,6,6,6,6,6,6,6,6
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,4,4,4,4,4,4,4,4,4,4
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,363,376,385,398,415,430,438,462,485,496
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,729,729,729,730,732,732,733,733,733,733
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,509,510,510,512,515,518,519,521,522,524
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,20,22,23,27,27,29,29,29,29,29
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,175,178,179,181,183,184,185,186,186,188
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,3740,3781,3822,3861,3907,3941,3983,4028,4082,4127
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,7
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,617,622,627,632,637,642,646,652,657,662
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,9959,9969,9976,9985,9988,9992,9996,9996,9879,9884
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,4,4,5,5,6,6,10,10,11,12
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,39,39,39,39,39,39,39,39,40,40
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,4172,4233,4305,4366,4442,4509,4578,4664,4726,4791
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,495,507,515,526,532,532,547,560,571,582
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,NaN,Thailand,15.870032,100.992541,0,0,0,0,0,0,...,58,58,58,58,58,58,58,58,58,58
237,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
238,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,27,27,27,27,27,27,27,27,27,27
239,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,12,12,12,12,13,14,15,15,15,15
240,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,57,60,63,64,68,71,71,71,71,73
241,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,6016,6039,6058,6080,6102,6121,6139,6163,6183,6209
242,NaN,US,40.000000,-100.000000,0,0,0,0,0,0,...,171821,173177,174255,175367,176350,176800,177245,178486,179708,180824
243,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,15,16,19,19,20,20,22,25,26,28
244,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,2152,2182,2225,2248,2286,2313,2335,2362,2399,2449
245,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,366,367,369,370,372,375,376,377,378,378
246,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,9
248,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
249,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
250,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,47,48,48,48,48,48,48,48,48,48
251,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
252,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
253,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,24
254,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
255,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,2,2,2,2,2,2,2,2,3,3
256,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,41381,41397,41403,41405,41423,41429,41433,41449,41465,41477
257,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,40,40,41,42,42,42,42,43,43,43
258,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,242,248,252,260,267,273,280,284,291,298
259,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,297,303,311,317,323,329,337,343,351,358
260,NaN,Vietnam,14.058324,108.277199,0,0,0,0,0,0,...,26,25,25,25,26,27,27,27,30,30
261,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,113,119,120,122,125,128,133,133,137,141
262,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
263,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,537,539,541,542,546,553,555,557,560,562
264,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,264,269,274,277,279,280,280,282,282,282
265,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,141,150,151,152,153,155,155,166,179,189

In [5]:
recoverGlobal=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
recoverGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,8/27/20
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,27166,27166,27681,28016,28016,28180,28360,28440,29042,29046
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3871,3928,3986,4096,4184,4332,4413,4530,4633,4791
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,27653,27971,28281,28587,28874,29142,29369,29587,29886,30157
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,869,875,875,875,875,875,877,877,893,893
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,667,698,742,804,814,818,877,977,977,1335
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,88,88,89,89,89,89,89,89,89,89
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,223531,228725,233651,239806,245781,251400,256789,263202,268801,274458
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,34982,35226,35476,35693,35907,35991,36049,36475,36726,36988
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,110,110,110,110,110,110,110,110,110,110
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,2994,2995,2994,2994,2994,2994,2994,2994,2994,2994
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,31,31,31,31,31,31,31,31,31,31
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1079,1081,1082,1082,1082,1082,1082,1083,1083,1084
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,451,452,452,452,452,456,456,456,456,456
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,216,216,216,216,216,216,216,216,216,216
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,9413,9729,12334,12940,13239,13708,14077,14572,14572,14837
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,633,633,633,633,634,634,635,636,637,637
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,20870,20958,21093,21260,21406,21558,21657,21888,22145,22317
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,32201,32363,32511,32682,32842,32993,33104,33190,33281,33364
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,203,209,211,221,221,227,227,227,227,227
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,43921,44278,44628,45166,45589,45981,46311,46673,47049,47370
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,162825,165738,168991,172615,175567,179091,182875,186756,190183,193458
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,122,123,123,124,126,132,132,132,139,140
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,67339,67647,67929,68256,68577,68839,68925,69097,69378,69650
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,18048,18078,18131,18165,18204,18225,18242,18291,18331,18360
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,38,38,38,43,44,44,45,48,54,54
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,1690,1690,1705,1705,1705,1705,1705,1705,1738,1738
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,103,103,108,110,112,112,117,118,118,119
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,38623,39965,41111,42141,43887,45396,47050,48875,50397,52521
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,10279,10711,10881,11157,11329,11329,11861,12081,12336,12480
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,136,136,136,136,136,136,199,199,199,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,NaN,Thailand,15.870032,100.992541,0,0,0,0,2,2,...,3199,3199,3218,3219,3220,3221,3229,3229,3237,3237
224,NaN,Timor-Leste,-8.874200,125.727500,0,0,0,0,0,0,...,24,25,25,25,25,25,25,25,25,25
225,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,868,875,878,891,903,910,914,919,946,946
226,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,140,140,140,162,165,165,165,178,192,192
227,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,1370,1395,1397,1420,1434,1443,1454,1456,1476,1504
228,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,232913,233915,234797,235569,236370,237165,237908,238795,239797,240792
229,NaN,US,40.000000,-100.000000,0,0,0,0,0,0,...,1898159,1925049,1947035,1965056,1985484,1997761,2020774,2053699,2084465,2101326
230,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1165,1188,1194,1199,1199,1199,1248,1267,1268,1268
231,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,50508,51358,52086,52769,53458,53968,54262,54657,55327,56149
232,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,57909,58022,58153,58296,58408,58488,58582,58754,59070,59472
233,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,3
234,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,147,147,147,147,149,149,150,151,151,151
235,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
236,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,202,202,202,202,202,202,202,202,202,202
237,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,545,545,545,545,545,545,545,545,545,545
238,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,13
239,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,195,197,200,200,201,201,203,203,203,216
240,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,312,312,312,312,312,312,312,312,312,312
241,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,12
242,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,56,56,102,102,102,102,102,102,102,102
243,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
244,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1219,1228,1242,1249,1264,1276,1295,1309,1322,1333
245,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,32062,32944,33261,33989,34576,34987,35551,35869,36402,37200
246,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,24561,25416,26330,27306,28453,29966,31080,32015,32931,34147
247,NaN,Vietnam,14.058324,108.277199,0,0,0,0,0,0,...,526,533,542,545,563,568,587,592,632,637
248,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,9939,10312,10682,11102,11103,11843,11870,13162,13929,14194
249,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,8
250,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1052,1055,1058,1058,1066,1086,1090,1091,1097,1098
251,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,8776,9126,9126,9126,9942,9942,10208,10400,10693,10840
252,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,4105,4442,4525,4587,4629,4872,4950,4961,5001,5010

In [6]:
confirmedGlobal['NewContryCode']=confirmedGlobal['Country/Region']+confirmedGlobal['Province/State'].fillna('')
deathGLobal['NewContryCode']=deathGLobal['Country/Region']+deathGLobal['Province/State'].fillna('')
recoverGlobal['NewContryCode']=recoverGlobal['Country/Region']+recoverGlobal['Province/State'].fillna(' ')
recoverGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,8/27/20,NewContryCode
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,27166,27681,28016,28016,28180,28360,28440,29042,29046,Afghanistan
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,3928,3986,4096,4184,4332,4413,4530,4633,4791,Albania
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,27971,28281,28587,28874,29142,29369,29587,29886,30157,Algeria
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,875,875,875,875,875,877,877,893,893,Andorra
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,698,742,804,814,818,877,977,977,1335,Angola
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,88,89,89,89,89,89,89,89,89,Antigua and Barbuda
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,228725,233651,239806,245781,251400,256789,263202,268801,274458,Argentina
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,35226,35476,35693,35907,35991,36049,36475,36726,36988,Armenia
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,110,110,110,110,110,110,110,110,110,AustraliaAustralian Capital Territory
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,2995,2994,2994,2994,2994,2994,2994,2994,2994,AustraliaNew South Wales
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,31,31,31,31,31,31,31,31,31,AustraliaNorthern Territory
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1081,1082,1082,1082,1082,1082,1083,1083,1084,AustraliaQueensland
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,452,452,452,452,456,456,456,456,456,AustraliaSouth Australia
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,216,216,216,216,216,216,216,216,216,AustraliaTasmania
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,9729,12334,12940,13239,13708,14077,14572,14572,14837,AustraliaVictoria
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,633,633,633,634,634,635,636,637,637,AustraliaWestern Australia
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,20958,21093,21260,21406,21558,21657,21888,22145,22317,Austria
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,32363,32511,32682,32842,32993,33104,33190,33281,33364,Azerbaijan
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,209,211,221,221,227,227,227,227,227,Bahamas
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,44278,44628,45166,45589,45981,46311,46673,47049,47370,Bahrain
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,165738,168991,172615,175567,179091,182875,186756,190183,193458,Bangladesh
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,123,123,124,126,132,132,132,139,140,Barbados
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,67647,67929,68256,68577,68839,68925,69097,69378,69650,Belarus
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,18078,18131,18165,18204,18225,18242,18291,18331,18360,Belgium
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,38,38,43,44,44,45,48,54,54,Belize
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,1690,1705,1705,1705,1705,1705,1705,1738,1738,Benin
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,103,108,110,112,112,117,118,118,119,Bhutan
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,39965,41111,42141,43887,45396,47050,48875,50397,52521,Bolivia
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,10711,10881,11157,11329,11329,11861,12081,12336,12480,Bosnia and Herzegovina
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,136,136,136,136,136,199,199,199,199,Botswana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,NaN,Thailand,15.870032,100.992541,0,0,0,0,2,2,...,3199,3218,3219,3220,3221,3229,3229,3237,3237,Thailand
224,NaN,Timor-Leste,-8.874200,125.727500,0,0,0,0,0,0,...,25,25,25,25,25,25,25,25,25,Timor-Leste
225,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,875,878,891,903,910,914,919,946,946,Togo
226,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,140,140,162,165,165,165,178,192,192,Trinidad and Tobago
227,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,1395,1397,1420,1434,1443,1454,1456,1476,1504,Tunisia
228,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,233915,234797,235569,236370,237165,237908,238795,239797,240792,Turkey
229,NaN,US,40.000000,-100.000000,0,0,0,0,0,0,...,1925049,1947035,1965056,1985484,1997761,2020774,2053699,2084465,2101326,US
230,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1188,1194,1199,1199,1199,1248,1267,1268,1268,Uganda
231,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,51358,52086,52769,53458,53968,54262,54657,55327,56149,Ukraine
232,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,58022,58153,58296,58408,58488,58582,58754,59070,59472,United Arab Emirates
233,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,United KingdomAnguilla
234,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,147,147,147,149,149,150,151,151,151,United KingdomBermuda
235,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,United KingdomBritish Virgin Islands
236,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,202,202,202,202,202,202,202,202,202,United KingdomCayman Islands
237,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,545,545,545,545,545,545,545,545,545,United KingdomChannel Islands
238,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,United KingdomFalkland Islands (Malvinas)
239,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,197,200,200,201,201,203,203,203,216,United KingdomGibraltar
240,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,312,312,312,312,312,312,312,312,312,United KingdomIsle of Man
241,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,United KingdomMontserrat
242,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,56,102,102,102,102,102,102,102,102,United KingdomTurks and Caicos Islands
243,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,United Kingdom
244,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1228,1242,1249,1264,1276,1295,1309,1322,1333,Uruguay
245,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,32944,33261,33989,34576,34987,35551,35869,36402,37200,Uzbekistan
246,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,25416,26330,27306,28453,29966,31080,32015,32931,34147,Venezuela
247,NaN,Vietnam,14.058324,108.277199,0,0,0,0,0,0,...,533,542,545,563,568,587,592,632,637,Vietnam
248,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,10312,10682,11102,11103,11843,11870,13162,13929,14194,West Bank and Gaza
249,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,Western Sahara
250,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1055,1058,1058,1066,1086,1090,1091,1097,1098,Yemen
251,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,9126,9126,9126,9942,9942,10208,10400,10693,10840,Zambia
252,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,4442,4525,4587,4629,4872,4950,4961,5001,5010,Zimbabwe

In [7]:
uniqueCOuntryName=pd.unique(confirmedGlobal['Country/Region'])
df2=confirmedGlobal[list(confirmedGlobal.columns[1:2])+list([confirmedGlobal.columns[-2]])]
df2.columns=['Country','values']
dictVal=[]
for i in range(df2.shape[0]):
    dictVal.append(dict(df2.ix[i]))
df2=df2.sort_values(by='values',ascending=False)
contryNames=list(df2['Country'].values)
(df2.head())

          Country   values
242            US  5867785
30         Brazil  3761391
143         India  3387500
208        Russia   972972
224  South Africa   618286

In [8]:
import dateutil
timestamps=[dateutil.parser.parse(i) for i in confirmedGlobal.columns[4:-1]]
datasetsForLine=[]
for i in uniqueCOuntryName:
    temp={}
    temp['label']=i
    temp['data']=confirmedGlobal[confirmedGlobal['Country/Region']==i][confirmedGlobal.columns[4:-1]].sum().values.tolist()
    datasetsForLine.append(temp)

In [9]:
df3=pd.read_json('https://cdn.jsdelivr.net/gh/highcharts/highcharts@v7.0.0/samples/data/world-population-density.json')
df3.head()

  code code3         name   value
0   AW   ABW        Aruba  582.34
1   AF   AFG  Afghanistan   53.08
2   AO   AGO       Angola   23.11
3   AL   ALB      Albania  104.97
4   AD   AND      Andorra  164.43

In [10]:
dataForMap=[]
for i in uniqueCOuntryName:
    try:
        tempdf=df3[df3['name']==i]
        temp={}
        temp["code3"]=list(tempdf['code3'].values)[0]
        temp["name"]=i
        temp["value"]=df2[df2['Country']==i]['values'].sum()
        temp["code"]=list(tempdf['code'].values)[0]
        dataForMap.append(temp)
    except:
        pass

In [11]:
dataForMap

[{'code3': 'AFG', 'name': 'Afghanistan', 'value': 38129, 'code': 'AF'},
 {'code3': 'ALB', 'name': 'Albania', 'value': 9083, 'code': 'AL'},
 {'code3': 'DZA', 'name': 'Algeria', 'value': 43016, 'code': 'DZ'},
 {'code3': 'AND', 'name': 'Andorra', 'value': 1098, 'code': 'AD'},
 {'code3': 'AGO', 'name': 'Angola', 'value': 2415, 'code': 'AO'},
 {'code3': 'ATG', 'name': 'Antigua and Barbuda', 'value': 94, 'code': 'AG'},
 {'code3': 'ARG', 'name': 'Argentina', 'value': 380292, 'code': 'AR'},
 {'code3': 'ARM', 'name': 'Armenia', 'value': 43270, 'code': 'AM'},
 {'code3': 'AUS', 'name': 'Australia', 'value': 25448, 'code': 'AU'},
 {'code3': 'AUT', 'name': 'Austria', 'value': 26361, 'code': 'AT'},
 {'code3': 'AZE', 'name': 'Azerbaijan', 'value': 35844, 'code': 'AZ'},
 {'code3': 'BHR', 'name': 'Bahrain', 'value': 50756, 'code': 'BH'},
 {'code3': 'BGD', 'name': 'Bangladesh', 'value': 304583, 'code': 'BD'},
 {'code3': 'BRB', 'name': 'Barbados', 'value': 165, 'code': 'BB'},
 {'code3': 'BLR', 'name': 'Belarus', 'value': 71165, 'code': 'BY'},
 {'code3': 'BEL', 'name': 'Belgium', 'value': 83500, 'code': 'BE'},
 {'code3': 'BLZ', 'name': 'Belize', 'value': 818, 'code': 'BZ'},
 {'code3': 'BEN', 'name': 'Benin', 'value': 2145, 'code': 'BJ'},
 {'code3': 'BTN', 'name': 'Bhutan', 'value': 184, 'code': 'BT'},
 {'code3': 'BOL', 'name': 'Bolivia', 'value': 113129, 'code': 'BO'},
 {'code3': 'BIH',
  'name': 'Bosnia and Herzegovina',
  'value': 18920,
  'code': 'BA'},
 {'code3': 'BWA', 'name': 'Botswana', 'value': 1562, 'code': 'BW'},
 {'code3': 'BRA', 'name': 'Brazil', 'value': 3761391, 'code': 'BR'},
 {'code3': 'BGR', 'name': 'Bulgaria', 'value': 15908, 'code': 'BG'},
 {'code3': 'BFA', 'name': 'Burkina Faso', 'value': 1352, 'code': 'BF'},
 {'code3': 'BDI', 'name': 'Burundi', 'value': 431, 'code': 'BI'},
 {'code3': 'CPV', 'name': 'Cabo Verde', 'value': 3699, 'code': 'CV'},
 {'code3': 'KHM', 'name': 'Cambodia', 'value': 273, 'code': 'KH'},
 {'code3': 'CMR', 'name': 'Cameroon', 'value': 19142, 'code': 'CM'},
 {'code3': 'CAN', 'name': 'Canada', 'value': 128836, 'code': 'CA'},
 {'code3': 'CAF',
  'name': 'Central African Republic',
  'value': 4698,
  'code': 'CF'},
 {'code3': 'TCD', 'name': 'Chad', 'value': 1004, 'code': 'TD'},
 {'code3': 'CHL', 'name': 'Chile', 'value': 404102, 'code': 'CL'},
 {'code3': 'CHN', 'name': 'China', 'value': 89814, 'code': 'CN'},
 {'code3': 'COL', 'name': 'Colombia', 'value': 581995, 'code': 'CO'},
 {'code3': 'COM', 'name': 'Comoros', 'value': 422, 'code': 'KM'},
 {'code3': 'CRI', 'name': 'Costa Rica', 'value': 37292, 'code': 'CR'},
 {'code3': 'CIV', 'name': "Cote d'Ivoire", 'value': 17702, 'code': 'CI'},
 {'code3': 'HRV', 'name': 'Croatia', 'value': 9192, 'code': 'HR'},
 {'code3': 'CUB', 'name': 'Cuba', 'value': 3806, 'code': 'CU'},
 {'code3': 'CYP', 'name': 'Cyprus', 'value': 1467, 'code': 'CY'},
 {'code3': 'DNK', 'name': 'Denmark', 'value': 17052, 'code': 'DK'},
 {'code3': 'DJI', 'name': 'Djibouti', 'value': 5383, 'code': 'DJ'},
 {'code3': 'DMA', 'name': 'Dominica', 'value': 20, 'code': 'DM'},
 {'code3': 'DOM', 'name': 'Dominican Republic', 'value': 92964, 'code': 'DO'},
 {'code3': 'ECU', 'name': 'Ecuador', 'value': 111219, 'code': 'EC'},
 {'code3': 'SLV', 'name': 'El Salvador', 'value': 25284, 'code': 'SV'},
 {'code3': 'GNQ', 'name': 'Equatorial Guinea', 'value': 4928, 'code': 'GQ'},
 {'code3': 'EST', 'name': 'Estonia', 'value': 2325, 'code': 'EE'},
 {'code3': 'ETH', 'name': 'Ethiopia', 'value': 46407, 'code': 'ET'},
 {'code3': 'FJI', 'name': 'Fiji', 'value': 28, 'code': 'FJ'},
 {'code3': 'FIN', 'name': 'Finland', 'value': 8019, 'code': 'FI'},
 {'code3': 'FRA', 'name': 'France', 'value': 297485, 'code': 'FR'},
 {'code3': 'GAB', 'name': 'Gabon', 'value': 8468, 'code': 'GA'},
 {'code3': 'GEO', 'name': 'Georgia', 'value': 1447, 'code': 'GE'},
 {'code3': 'DEU', 'name': 'Germany', 'value': 240571, 'code': 'DE'},
 {'code3': 'GHA', 'name': 'Ghana', 'value': 43841, 'code': 'GH'},
 {'code3': 'GRC', 'name': 'Greece', 'value': 9531, 'code': 'GR'},
 {'code3': 'GRD', 'name': 'Grenada', 'value': 24, 'code': 'GD'},
 {'code3': 'GTM', 'name': 'Guatemala', 'value': 71856, 'code': 'GT'},
 {'code3': 'GIN', 'name': 'Guinea', 'value': 9213, 'code': 'GN'},
 {'code3': 'GNB', 'name': 'Guinea-Bissau', 'value': 2205, 'code': 'GW'},
 {'code3': 'GUY', 'name': 'Guyana', 'value': 1140, 'code': 'GY'},
 {'code3': 'HTI', 'name': 'Haiti', 'value': 8151, 'code': 'HT'},
 {'code3': 'HND', 'name': 'Honduras', 'value': 57669, 'code': 'HN'},
 {'code3': 'HUN', 'name': 'Hungary', 'value': 5379, 'code': 'HU'},
 {'code3': 'ISL', 'name': 'Iceland', 'value': 2087, 'code': 'IS'},
 {'code3': 'IND', 'name': 'India', 'value': 3387500, 'code': 'IN'},
 {'code3': 'IDN', 'name': 'Indonesia', 'value': 162884, 'code': 'ID'},
 {'code3': 'IRQ', 'name': 'Iraq', 'value': 219435, 'code': 'IQ'},
 {'code3': 'IRL', 'name': 'Ireland', 'value': 28453, 'code': 'IE'},
 {'code3': 'ISR', 'name': 'Israel', 'value': 110403, 'code': 'IL'},
 {'code3': 'ITA', 'name': 'Italy', 'value': 263949, 'code': 'IT'},
 {'code3': 'JAM', 'name': 'Jamaica', 'value': 1870, 'code': 'JM'},
 {'code3': 'JPN', 'name': 'Japan', 'value': 65653, 'code': 'JP'},
 {'code3': 'JOR', 'name': 'Jordan', 'value': 1801, 'code': 'JO'},
 {'code3': 'KAZ', 'name': 'Kazakhstan', 'value': 105408, 'code': 'KZ'},
 {'code3': 'KEN', 'name': 'Kenya', 'value': 33389, 'code': 'KE'},
 {'code3': 'KWT', 'name': 'Kuwait', 'value': 82945, 'code': 'KW'},
 {'code3': 'LVA', 'name': 'Latvia', 'value': 1366, 'code': 'LV'},
 {'code3': 'LBN', 'name': 'Lebanon', 'value': 14937, 'code': 'LB'},
 {'code3': 'LSO', 'name': 'Lesotho', 'value': 1051, 'code': 'LS'},
 {'code3': 'LBR', 'name': 'Liberia', 'value': 1298, 'code': 'LR'},
 {'code3': 'LBY', 'name': 'Libya', 'value': 12274, 'code': 'LY'},
 {'code3': 'LIE', 'name': 'Liechtenstein', 'value': 105, 'code': 'LI'},
 {'code3': 'LTU', 'name': 'Lithuania', 'value': 2762, 'code': 'LT'},
 {'code3': 'LUX', 'name': 'Luxembourg', 'value': 7928, 'code': 'LU'},
 {'code3': 'MDG', 'name': 'Madagascar', 'value': 14592, 'code': 'MG'},
 {'code3': 'MWI', 'name': 'Malawi', 'value': 5496, 'code': 'MW'},
 {'code3': 'MYS', 'name': 'Malaysia', 'value': 9296, 'code': 'MY'},
 {'code3': 'MDV', 'name': 'Maldives', 'value': 7329, 'code': 'MV'},
 {'code3': 'MLI', 'name': 'Mali', 'value': 2730, 'code': 'ML'},
 {'code3': 'MLT', 'name': 'Malta', 'value': 1788, 'code': 'MT'},
 {'code3': 'MRT', 'name': 'Mauritania', 'value': 6993, 'code': 'MR'},
 {'code3': 'MUS', 'name': 'Mauritius', 'value': 355, 'code': 'MU'},
 {'code3': 'MEX', 'name': 'Mexico', 'value': 579914, 'code': 'MX'},
 {'code3': 'MDA', 'name': 'Moldova', 'value': 35546, 'code': 'MD'},
 {'code3': 'MCO', 'name': 'Monaco', 'value': 154, 'code': 'MC'},
 {'code3': 'MNG', 'name': 'Mongolia', 'value': 301, 'code': 'MN'},
 {'code3': 'MNE', 'name': 'Montenegro', 'value': 4558, 'code': 'ME'},
 {'code3': 'MAR', 'name': 'Morocco', 'value': 57085, 'code': 'MA'},
 {'code3': 'MOZ', 'name': 'Mozambique', 'value': 3651, 'code': 'MZ'},
 {'code3': 'NAM', 'name': 'Namibia', 'value': 6712, 'code': 'NA'},
 {'code3': 'NPL', 'name': 'Nepal', 'value': 35529, 'code': 'NP'},
 {'code3': 'NLD', 'name': 'Netherlands', 'value': 70984, 'code': 'NL'},
 {'code3': 'NZL', 'name': 'New Zealand', 'value': 1714, 'code': 'NZ'},
 {'code3': 'NIC', 'name': 'Nicaragua', 'value': 4494, 'code': 'NI'},
 {'code3': 'NER', 'name': 'Niger', 'value': 1173, 'code': 'NE'},
 {'code3': 'NGA', 'name': 'Nigeria', 'value': 53317, 'code': 'NG'},
 {'code3': 'NOR', 'name': 'Norway', 'value': 10542, 'code': 'NO'},
 {'code3': 'OMN', 'name': 'Oman', 'value': 85005, 'code': 'OM'},
 {'code3': 'PAK', 'name': 'Pakistan', 'value': 294638, 'code': 'PK'},
 {'code3': 'PAN', 'name': 'Panama', 'value': 89982, 'code': 'PA'},
 {'code3': 'PNG', 'name': 'Papua New Guinea', 'value': 424, 'code': 'PG'},
 {'code3': 'PRY', 'name': 'Paraguay', 'value': 15290, 'code': 'PY'},
 {'code3': 'PER', 'name': 'Peru', 'value': 613378, 'code': 'PE'},
 {'code3': 'PHL', 'name': 'Philippines', 'value': 205581, 'code': 'PH'},
 {'code3': 'POL', 'name': 'Poland', 'value': 64689, 'code': 'PL'},
 {'code3': 'PRT', 'name': 'Portugal', 'value': 56673, 'code': 'PT'},
 {'code3': 'QAT', 'name': 'Qatar', 'value': 117988, 'code': 'QA'},
 {'code3': 'ROU', 'name': 'Romania', 'value': 83150, 'code': 'RO'},
 {'code3': 'RWA', 'name': 'Rwanda', 'value': 3672, 'code': 'RW'},
 {'code3': 'SMR', 'name': 'San Marino', 'value': 710, 'code': 'SM'},
 {'code3': 'STP', 'name': 'Sao Tome and Principe', 'value': 894, 'code': 'ST'},
 {'code3': 'SAU', 'name': 'Saudi Arabia', 'value': 311855, 'code': 'SA'},
 {'code3': 'SEN', 'name': 'Senegal', 'value': 13294, 'code': 'SN'},
 {'code3': 'SRB', 'name': 'Serbia', 'value': 31099, 'code': 'RS'},
 {'code3': 'SYC', 'name': 'Seychelles', 'value': 136, 'code': 'SC'},
 {'code3': 'SLE', 'name': 'Sierra Leone', 'value': 2013, 'code': 'SL'},
 {'code3': 'SGP', 'name': 'Singapore', 'value': 56572, 'code': 'SG'},
 {'code3': 'SVN', 'name': 'Slovenia', 'value': 2755, 'code': 'SI'},
 {'code3': 'SOM', 'name': 'Somalia', 'value': 3275, 'code': 'SO'},
 {'code3': 'ZAF', 'name': 'South Africa', 'value': 618286, 'code': 'ZA'},
 {'code3': 'ESP', 'name': 'Spain', 'value': 429507, 'code': 'ES'},
 {'code3': 'LKA', 'name': 'Sri Lanka', 'value': 2986, 'code': 'LK'},
 {'code3': 'SDN', 'name': 'Sudan', 'value': 13045, 'code': 'SD'},
 {'code3': 'SUR', 'name': 'Suriname', 'value': 3793, 'code': 'SR'},
 {'code3': 'SWE', 'name': 'Sweden', 'value': 83898, 'code': 'SE'},
 {'code3': 'CHE', 'name': 'Switzerland', 'value': 41006, 'code': 'CH'},
 {'code3': 'TJK', 'name': 'Tajikistan', 'value': 8449, 'code': 'TJ'},
 {'code3': 'TZA', 'name': 'Tanzania', 'value': 509, 'code': 'TZ'},
 {'code3': 'THA', 'name': 'Thailand', 'value': 3410, 'code': 'TH'},
 {'code3': 'TLS', 'name': 'Timor-Leste', 'value': 27, 'code': 'TL'},
 {'code3': 'TGO', 'name': 'Togo', 'value': 1326, 'code': 'TG'},
 {'code3': 'TTO', 'name': 'Trinidad and Tobago', 'value': 1429, 'code': 'TT'},
 {'code3': 'TUN', 'name': 'Tunisia', 'value': 3323, 'code': 'TN'},
 {'code3': 'TUR', 'name': 'Turkey', 'value': 263998, 'code': 'TR'},
 {'code3': 'UGA', 'name': 'Uganda', 'value': 2679, 'code': 'UG'},
 {'code3': 'UKR', 'name': 'Ukraine', 'value': 114663, 'code': 'UA'},
 {'code3': 'ARE',
  'name': 'United Arab Emirates',
  'value': 68511,
  'code': 'AE'},
 {'code3': 'GBR', 'name': 'United Kingdom', 'value': 332509, 'code': 'GB'},
 {'code3': 'URY', 'name': 'Uruguay', 'value': 1551, 'code': 'UY'},
 {'code3': 'UZB', 'name': 'Uzbekistan', 'value': 40447, 'code': 'UZ'},
 {'code3': 'VNM', 'name': 'Vietnam', 'value': 1036, 'code': 'VN'},
 {'code3': 'PSE', 'name': 'West Bank and Gaza', 'value': 20677, 'code': 'PS'},
 {'code3': 'ZMB', 'name': 'Zambia', 'value': 11601, 'code': 'ZM'},
 {'code3': 'ZWE', 'name': 'Zimbabwe', 'value': 6292, 'code': 'ZW'}]

In [12]:
df3=confirmedGlobal[list(confirmedGlobal.columns[1:2])+list(list(confirmedGlobal.columns.values)[-6:-1])]
df3.head()

  Country/Region  8/23/20  8/24/20  8/25/20  8/26/20  8/27/20
0    Afghanistan    37999    38054    38070    38113    38129
1        Albania     8427     8605     8759     8927     9083
2        Algeria    41460    41858    42228    42619    43016
3        Andorra     1045     1060     1060     1098     1098
4         Angola     2171     2222     2283     2332     2415

In [13]:
dataForheatMap=[]
for i in contryNames:
    try:
        tempdf=df3[df3['Country/Region']==i]
        temp={}
        temp["name"]=i
        temp["data"]=[{'x':j,'y':k} for j,k in zip(tempdf[tempdf.columns[1:]].sum().index,tempdf[tempdf.columns[1:]].sum().values)]
        dataForheatMap.append(temp)
    except:
        pass
dataForheatMap

[{'name': 'US',
  'data': [{'x': '8/23/20', 'y': 5701645},
   {'x': '8/24/20', 'y': 5739536},
   {'x': '8/25/20', 'y': 5777710},
   {'x': '8/26/20', 'y': 5821819},
   {'x': '8/27/20', 'y': 5867785}]},
 {'name': 'Brazil',
  'data': [{'x': '8/23/20', 'y': 3605783},
   {'x': '8/24/20', 'y': 3622861},
   {'x': '8/25/20', 'y': 3669995},
   {'x': '8/26/20', 'y': 3717156},
   {'x': '8/27/20', 'y': 3761391}]},
 {'name': 'India',
  'data': [{'x': '8/23/20', 'y': 3106348},
   {'x': '8/24/20', 'y': 3167323},
   {'x': '8/25/20', 'y': 3224547},
   {'x': '8/26/20', 'y': 3310234},
   {'x': '8/27/20', 'y': 3387500}]},
 {'name': 'Russia',
  'data': [{'x': '8/23/20', 'y': 954328},
   {'x': '8/24/20', 'y': 959016},
   {'x': '8/25/20', 'y': 963655},
   {'x': '8/26/20', 'y': 968297},
   {'x': '8/27/20', 'y': 972972}]},
 {'name': 'South Africa',
  'data': [{'x': '8/23/20', 'y': 609773},
   {'x': '8/24/20', 'y': 611450},
   {'x': '8/25/20', 'y': 613017},
   {'x': '8/26/20', 'y': 615701},
   {'x': '8/27/20', 'y': 618286}]},
 {'name': 'Peru',
  'data': [{'x': '8/23/20', 'y': 585236},
   {'x': '8/24/20', 'y': 594326},
   {'x': '8/25/20', 'y': 600438},
   {'x': '8/26/20', 'y': 607382},
   {'x': '8/27/20', 'y': 613378}]},
 {'name': 'Colombia',
  'data': [{'x': '8/23/20', 'y': 541139},
   {'x': '8/24/20', 'y': 551688},
   {'x': '8/25/20', 'y': 562113},
   {'x': '8/26/20', 'y': 572243},
   {'x': '8/27/20', 'y': 581995}]},
 {'name': 'Mexico',
  'data': [{'x': '8/23/20', 'y': 560164},
   {'x': '8/24/20', 'y': 563705},
   {'x': '8/25/20', 'y': 568621},
   {'x': '8/26/20', 'y': 573888},
   {'x': '8/27/20', 'y': 579914}]},
 {'name': 'Spain',
  'data': [{'x': '8/23/20', 'y': 386054},
   {'x': '8/24/20', 'y': 405436},
   {'x': '8/25/20', 'y': 412553},
   {'x': '8/26/20', 'y': 419849},
   {'x': '8/27/20', 'y': 429507}]},
 {'name': 'Chile',
  'data': [{'x': '8/23/20', 'y': 397665},
   {'x': '8/24/20', 'y': 399568},
   {'x': '8/25/20', 'y': 400985},
   {'x': '8/26/20', 'y': 402365},
   {'x': '8/27/20', 'y': 404102}]},
 {'name': 'Argentina',
  'data': [{'x': '8/23/20', 'y': 342154},
   {'x': '8/24/20', 'y': 350867},
   {'x': '8/25/20', 'y': 359638},
   {'x': '8/26/20', 'y': 370188},
   {'x': '8/27/20', 'y': 380292}]},
 {'name': 'Iran',
  'data': [{'x': '8/23/20', 'y': 358905},
   {'x': '8/24/20', 'y': 361150},
   {'x': '8/25/20', 'y': 363363},
   {'x': '8/26/20', 'y': 365606},
   {'x': '8/27/20', 'y': 367796}]},
 {'name': 'United Kingdom',
  'data': [{'x': '8/23/20', 'y': 327643},
   {'x': '8/24/20', 'y': 328620},
   {'x': '8/25/20', 'y': 329821},
   {'x': '8/26/20', 'y': 330967},
   {'x': '8/27/20', 'y': 332509}]},
 {'name': 'Saudi Arabia',
  'data': [{'x': '8/23/20', 'y': 307479},
   {'x': '8/24/20', 'y': 308654},
   {'x': '8/25/20', 'y': 309768},
   {'x': '8/26/20', 'y': 310836},
   {'x': '8/27/20', 'y': 311855}]},
 {'name': 'Bangladesh',
  'data': [{'x': '8/23/20', 'y': 294598},
   {'x': '8/24/20', 'y': 297083},
   {'x': '8/25/20', 'y': 299628},
   {'x': '8/26/20', 'y': 302147},
   {'x': '8/27/20', 'y': 304583}]},
 {'name': 'Pakistan',
  'data': [{'x': '8/23/20', 'y': 293261},
   {'x': '8/24/20', 'y': 293261},
   {'x': '8/25/20', 'y': 293711},
   {'x': '8/26/20', 'y': 294193},
   {'x': '8/27/20', 'y': 294638}]},
 {'name': 'France',
  'data': [{'x': '8/23/20', 'y': 280459},
   {'x': '8/24/20', 'y': 282414},
   {'x': '8/25/20', 'y': 285902},
   {'x': '8/26/20', 'y': 291374},
   {'x': '8/27/20', 'y': 297485}]},
 {'name': 'Turkey',
  'data': [{'x': '8/23/20', 'y': 258249},
   {'x': '8/24/20', 'y': 259692},
   {'x': '8/25/20', 'y': 261194},
   {'x': '8/26/20', 'y': 262507},
   {'x': '8/27/20', 'y': 263998}]},
 {'name': 'Italy',
  'data': [{'x': '8/23/20', 'y': 259345},
   {'x': '8/24/20', 'y': 260298},
   {'x': '8/25/20', 'y': 261174},
   {'x': '8/26/20', 'y': 262540},
   {'x': '8/27/20', 'y': 263949}]},
 {'name': 'Germany',
  'data': [{'x': '8/23/20', 'y': 234494},
   {'x': '8/24/20', 'y': 236122},
   {'x': '8/25/20', 'y': 237583},
   {'x': '8/26/20', 'y': 239010},
   {'x': '8/27/20', 'y': 240571}]},
 {'name': 'Iraq',
  'data': [{'x': '8/23/20', 'y': 204341},
   {'x': '8/24/20', 'y': 207985},
   {'x': '8/25/20', 'y': 211947},
   {'x': '8/26/20', 'y': 215784},
   {'x': '8/27/20', 'y': 219435}]},
 {'name': 'Philippines',
  'data': [{'x': '8/23/20', 'y': 189601},
   {'x': '8/24/20', 'y': 194252},
   {'x': '8/25/20', 'y': 197164},
   {'x': '8/26/20', 'y': 202361},
   {'x': '8/27/20', 'y': 205581}]},
 {'name': 'Indonesia',
  'data': [{'x': '8/23/20', 'y': 153535},
   {'x': '8/24/20', 'y': 155412},
   {'x': '8/25/20', 'y': 157859},
   {'x': '8/26/20', 'y': 160165},
   {'x': '8/27/20', 'y': 162884}]},
 {'name': 'Qatar',
  'data': [{'x': '8/23/20', 'y': 117008},
   {'x': '8/24/20', 'y': 117266},
   {'x': '8/25/20', 'y': 117498},
   {'x': '8/26/20', 'y': 117742},
   {'x': '8/27/20', 'y': 117988}]},
 {'name': 'Ukraine',
  'data': [{'x': '8/23/20', 'y': 107379},
   {'x': '8/24/20', 'y': 109234},
   {'x': '8/25/20', 'y': 110949},
   {'x': '8/26/20', 'y': 112653},
   {'x': '8/27/20', 'y': 114663}]},
 {'name': 'Bolivia',
  'data': [{'x': '8/23/20', 'y': 109149},
   {'x': '8/24/20', 'y': 110148},
   {'x': '8/25/20', 'y': 110999},
   {'x': '8/26/20', 'y': 112094},
   {'x': '8/27/20', 'y': 113129}]},
 {'name': 'Ecuador',
  'data': [{'x': '8/23/20', 'y': 107769},
   {'x': '8/24/20', 'y': 108289},
   {'x': '8/25/20', 'y': 109030},
   {'x': '8/26/20', 'y': 110549},
   {'x': '8/27/20', 'y': 111219}]},
 {'name': 'Israel',
  'data': [{'x': '8/23/20', 'y': 102663},
   {'x': '8/24/20', 'y': 104472},
   {'x': '8/25/20', 'y': 106460},
   {'x': '8/26/20', 'y': 108403},
   {'x': '8/27/20', 'y': 110403}]},
 {'name': 'Kazakhstan',
  'data': [{'x': '8/23/20', 'y': 104718},
   {'x': '8/24/20', 'y': 104902},
   {'x': '8/25/20', 'y': 105075},
   {'x': '8/26/20', 'y': 105243},
   {'x': '8/27/20', 'y': 105408}]},
 {'name': 'Egypt',
  'data': [{'x': '8/23/20', 'y': 97340},
   {'x': '8/24/20', 'y': 97478},
   {'x': '8/25/20', 'y': 97619},
   {'x': '8/26/20', 'y': 97825},
   {'x': '8/27/20', 'y': 98062}]},
 {'name': 'Dominican Republic',
  'data': [{'x': '8/23/20', 'y': 91161},
   {'x': '8/24/20', 'y': 91608},
   {'x': '8/25/20', 'y': 92217},
   {'x': '8/26/20', 'y': 92557},
   {'x': '8/27/20', 'y': 92964}]},
 {'name': 'Panama',
  'data': [{'x': '8/23/20', 'y': 86900},
   {'x': '8/24/20', 'y': 87485},
   {'x': '8/25/20', 'y': 88381},
   {'x': '8/26/20', 'y': 89082},
   {'x': '8/27/20', 'y': 89982}]},
 {'name': 'Oman',
  'data': [{'x': '8/23/20', 'y': 83769},
   {'x': '8/24/20', 'y': 84509},
   {'x': '8/25/20', 'y': 84652},
   {'x': '8/26/20', 'y': 84818},
   {'x': '8/27/20', 'y': 85005}]},
 {'name': 'Sweden',
  'data': [{'x': '8/23/20', 'y': 86068},
   {'x': '8/24/20', 'y': 86721},
   {'x': '8/25/20', 'y': 86891},
   {'x': '8/26/20', 'y': 87072},
   {'x': '8/27/20', 'y': 83898}]},
 {'name': 'Belgium',
  'data': [{'x': '8/23/20', 'y': 81936},
   {'x': '8/24/20', 'y': 82092},
   {'x': '8/25/20', 'y': 82447},
   {'x': '8/26/20', 'y': 83030},
   {'x': '8/27/20', 'y': 83500}]},
 {'name': 'Romania',
  'data': [{'x': '8/23/20', 'y': 78505},
   {'x': '8/24/20', 'y': 79330},
   {'x': '8/25/20', 'y': 80390},
   {'x': '8/26/20', 'y': 81646},
   {'x': '8/27/20', 'y': 83150}]},
 {'name': 'Kuwait',
  'data': [{'x': '8/23/20', 'y': 80528},
   {'x': '8/24/20', 'y': 80960},
   {'x': '8/25/20', 'y': 81573},
   {'x': '8/26/20', 'y': 82271},
   {'x': '8/27/20', 'y': 82945}]},
 {'name': 'Guatemala',
  'data': [{'x': '8/23/20', 'y': 68188},
   {'x': '8/24/20', 'y': 68533},
   {'x': '8/25/20', 'y': 69651},
   {'x': '8/26/20', 'y': 70714},
   {'x': '8/27/20', 'y': 71856}]},
 {'name': 'Belarus',
  'data': [{'x': '8/23/20', 'y': 70468},
   {'x': '8/24/20', 'y': 70645},
   {'x': '8/25/20', 'y': 70727},
   {'x': '8/26/20', 'y': 70974},
   {'x': '8/27/20', 'y': 71165}]},
 {'name': 'Netherlands',
  'data': [{'x': '8/23/20', 'y': 68570},
   {'x': '8/24/20', 'y': 69224},
   {'x': '8/25/20', 'y': 69683},
   {'x': '8/26/20', 'y': 70382},
   {'x': '8/27/20', 'y': 70984}]},
 {'name': 'United Arab Emirates',
  'data': [{'x': '8/23/20', 'y': 67007},
   {'x': '8/24/20', 'y': 67282},
   {'x': '8/25/20', 'y': 67621},
   {'x': '8/26/20', 'y': 68020},
   {'x': '8/27/20', 'y': 68511}]},
 {'name': 'China',
  'data': [{'x': '8/23/20', 'y': 89695},
   {'x': '8/24/20', 'y': 89718},
   {'x': '8/25/20', 'y': 89752},
   {'x': '8/26/20', 'y': 89784},
   {'x': '8/27/20', 'y': 89814}]},
 {'name': 'Japan',
  'data': [{'x': '8/23/20', 'y': 62658},
   {'x': '8/24/20', 'y': 63158},
   {'x': '8/25/20', 'y': 63888},
   {'x': '8/26/20', 'y': 64779},
   {'x': '8/27/20', 'y': 65653}]},
 {'name': 'Poland',
  'data': [{'x': '8/23/20', 'y': 61762},
   {'x': '8/24/20', 'y': 62310},
   {'x': '8/25/20', 'y': 63073},
   {'x': '8/26/20', 'y': 63802},
   {'x': '8/27/20', 'y': 64689}]},
 {'name': 'Canada',
  'data': [{'x': '8/23/20', 'y': 126817},
   {'x': '8/24/20', 'y': 127594},
   {'x': '8/25/20', 'y': 127903},
   {'x': '8/26/20', 'y': 128380},
   {'x': '8/27/20', 'y': 128836}]},
 {'name': 'Honduras',
  'data': [{'x': '8/23/20', 'y': 54511},
   {'x': '8/24/20', 'y': 55479},
   {'x': '8/25/20', 'y': 55877},
   {'x': '8/26/20', 'y': 56649},
   {'x': '8/27/20', 'y': 57669}]},
 {'name': 'Morocco',
  'data': [{'x': '8/23/20', 'y': 52349},
   {'x': '8/24/20', 'y': 53252},
   {'x': '8/25/20', 'y': 54528},
   {'x': '8/26/20', 'y': 55864},
   {'x': '8/27/20', 'y': 57085}]},
 {'name': 'Portugal',
  'data': [{'x': '8/23/20', 'y': 55597},
   {'x': '8/24/20', 'y': 55720},
   {'x': '8/25/20', 'y': 55912},
   {'x': '8/26/20', 'y': 56274},
   {'x': '8/27/20', 'y': 56673}]},
 {'name': 'Singapore',
  'data': [{'x': '8/23/20', 'y': 56353},
   {'x': '8/24/20', 'y': 56404},
   {'x': '8/25/20', 'y': 56435},
   {'x': '8/26/20', 'y': 56495},
   {'x': '8/27/20', 'y': 56572}]},
 {'name': 'Nigeria',
  'data': [{'x': '8/23/20', 'y': 52227},
   {'x': '8/24/20', 'y': 52548},
   {'x': '8/25/20', 'y': 52800},
   {'x': '8/26/20', 'y': 53021},
   {'x': '8/27/20', 'y': 53317}]},
 {'name': 'Bahrain',
  'data': [{'x': '8/23/20', 'y': 49330},
   {'x': '8/24/20', 'y': 49719},
   {'x': '8/25/20', 'y': 50076},
   {'x': '8/26/20', 'y': 50393},
   {'x': '8/27/20', 'y': 50756}]},
 {'name': 'Ethiopia',
  'data': [{'x': '8/23/20', 'y': 40671},
   {'x': '8/24/20', 'y': 42143},
   {'x': '8/25/20', 'y': 43688},
   {'x': '8/26/20', 'y': 45221},
   {'x': '8/27/20', 'y': 46407}]},
 {'name': 'Ghana',
  'data': [{'x': '8/23/20', 'y': 43505},
   {'x': '8/24/20', 'y': 43622},
   {'x': '8/25/20', 'y': 43717},
   {'x': '8/26/20', 'y': 43769},
   {'x': '8/27/20', 'y': 43841}]},
 {'name': 'Canada',
  'data': [{'x': '8/23/20', 'y': 126817},
   {'x': '8/24/20', 'y': 127594},
   {'x': '8/25/20', 'y': 127903},
   {'x': '8/26/20', 'y': 128380},
   {'x': '8/27/20', 'y': 128836}]},
 {'name': 'Kyrgyzstan',
  'data': [{'x': '8/23/20', 'y': 43023},
   {'x': '8/24/20', 'y': 43126},
   {'x': '8/25/20', 'y': 43245},
   {'x': '8/26/20', 'y': 43358},
   {'x': '8/27/20', 'y': 43459}]},
 {'name': 'Armenia',
  'data': [{'x': '8/23/20', 'y': 42792},
   {'x': '8/24/20', 'y': 42825},
   {'x': '8/25/20', 'y': 42936},
   {'x': '8/26/20', 'y': 43067},
   {'x': '8/27/20', 'y': 43270}]},
 {'name': 'Algeria',
  'data': [{'x': '8/23/20', 'y': 41460},
   {'x': '8/24/20', 'y': 41858},
   {'x': '8/25/20', 'y': 42228},
   {'x': '8/26/20', 'y': 42619},
   {'x': '8/27/20', 'y': 43016}]},
 {'name': 'Venezuela',
  'data': [{'x': '8/23/20', 'y': 39564},
   {'x': '8/24/20', 'y': 40338},
   {'x': '8/25/20', 'y': 41158},
   {'x': '8/26/20', 'y': 41965},
   {'x': '8/27/20', 'y': 42898}]},
 {'name': 'Switzerland',
  'data': [{'x': '8/23/20', 'y': 39903},
   {'x': '8/24/20', 'y': 40060},
   {'x': '8/25/20', 'y': 40262},
   {'x': '8/26/20', 'y': 40645},
   {'x': '8/27/20', 'y': 41006}]},
 {'name': 'Uzbekistan',
  'data': [{'x': '8/23/20', 'y': 38946},
   {'x': '8/24/20', 'y': 39348},
   {'x': '8/25/20', 'y': 39641},
   {'x': '8/26/20', 'y': 39964},
   {'x': '8/27/20', 'y': 40447}]},
 {'name': 'Afghanistan',
  'data': [{'x': '8/23/20', 'y': 37999},
   {'x': '8/24/20', 'y': 38054},
   {'x': '8/25/20', 'y': 38070},
   {'x': '8/26/20', 'y': 38113},
   {'x': '8/27/20', 'y': 38129}]},
 {'name': 'Costa Rica',
  'data': [{'x': '8/23/20', 'y': 33820},
   {'x': '8/24/20', 'y': 34463},
   {'x': '8/25/20', 'y': 35305},
   {'x': '8/26/20', 'y': 36307},
   {'x': '8/27/20', 'y': 37292}]},
 {'name': 'Azerbaijan',
  'data': [{'x': '8/23/20', 'y': 35274},
   {'x': '8/24/20', 'y': 35426},
   {'x': '8/25/20', 'y': 35559},
   {'x': '8/26/20', 'y': 35707},
   {'x': '8/27/20', 'y': 35844}]},
 {'name': 'Moldova',
  'data': [{'x': '8/23/20', 'y': 33478},
   {'x': '8/24/20', 'y': 33828},
   {'x': '8/25/20', 'y': 34358},
   {'x': '8/26/20', 'y': 34982},
   {'x': '8/27/20', 'y': 35546}]},
 {'name': 'Nepal',
  'data': [{'x': '8/23/20', 'y': 31935},
   {'x': '8/24/20', 'y': 32678},
   {'x': '8/25/20', 'y': 33533},
   {'x': '8/26/20', 'y': 34418},
   {'x': '8/27/20', 'y': 35529}]},
 {'name': 'Kenya',
  'data': [{'x': '8/23/20', 'y': 32364},
   {'x': '8/24/20', 'y': 32557},
   {'x': '8/25/20', 'y': 32803},
   {'x': '8/26/20', 'y': 33016},
   {'x': '8/27/20', 'y': 33389}]},
 {'name': 'Serbia',
  'data': [{'x': '8/23/20', 'y': 30657},
   {'x': '8/24/20', 'y': 30714},
   {'x': '8/25/20', 'y': 30820},
   {'x': '8/26/20', 'y': 30974},
   {'x': '8/27/20', 'y': 31099}]},
 {'name': 'Ireland',
  'data': [{'x': '8/23/20', 'y': 27969},
   {'x': '8/24/20', 'y': 28116},
   {'x': '8/25/20', 'y': 28201},
   {'x': '8/26/20', 'y': 28363},
   {'x': '8/27/20', 'y': 28453}]},
 {'name': 'Austria',
  'data': [{'x': '8/23/20', 'y': 25253},
   {'x': '8/24/20', 'y': 25495},
   {'x': '8/25/20', 'y': 25706},
   {'x': '8/26/20', 'y': 26033},
   {'x': '8/27/20', 'y': 26361}]},
 {'name': 'El Salvador',
  'data': [{'x': '8/23/20', 'y': 24622},
   {'x': '8/24/20', 'y': 24811},
   {'x': '8/25/20', 'y': 24986},
   {'x': '8/26/20', 'y': 25140},
   {'x': '8/27/20', 'y': 25284}]},
 {'name': 'Czechia',
  'data': [{'x': '8/23/20', 'y': 21923},
   {'x': '8/24/20', 'y': 22181},
   {'x': '8/25/20', 'y': 22548},
   {'x': '8/26/20', 'y': 22951},
   {'x': '8/27/20', 'y': 23169}]},
 {'name': 'West Bank and Gaza',
  'data': [{'x': '8/23/20', 'y': 18802},
   {'x': '8/24/20', 'y': 19213},
   {'x': '8/25/20', 'y': 19678},
   {'x': '8/26/20', 'y': 20155},
   {'x': '8/27/20', 'y': 20677}]},
 {'name': 'Cameroon',
  'data': [{'x': '8/23/20', 'y': 18762},
   {'x': '8/24/20', 'y': 18762},
   {'x': '8/25/20', 'y': 18973},
   {'x': '8/26/20', 'y': 18973},
   {'x': '8/27/20', 'y': 19142}]},
 {'name': 'Korea, South',
  'data': [{'x': '8/23/20', 'y': 17665},
   {'x': '8/24/20', 'y': 17945},
   {'x': '8/25/20', 'y': 18265},
   {'x': '8/26/20', 'y': 18706},
   {'x': '8/27/20', 'y': 19077}]},
 {'name': 'Bosnia and Herzegovina',
  'data': [{'x': '8/23/20', 'y': 17715},
   {'x': '8/24/20', 'y': 18029},
   {'x': '8/25/20', 'y': 18326},
   {'x': '8/26/20', 'y': 18609},
   {'x': '8/27/20', 'y': 18920}]},
 {'name': 'Australia',
  'data': [{'x': '8/23/20', 'y': 24915},
   {'x': '8/24/20', 'y': 25053},
   {'x': '8/25/20', 'y': 25204},
   {'x': '8/26/20', 'y': 25322},
   {'x': '8/27/20', 'y': 25448}]},
 {'name': "Cote d'Ivoire",
  'data': [{'x': '8/23/20', 'y': 17471},
   {'x': '8/24/20', 'y': 17506},
   {'x': '8/25/20', 'y': 17562},
   {'x': '8/26/20', 'y': 17603},
   {'x': '8/27/20', 'y': 17702}]},
 {'name': 'Denmark',
  'data': [{'x': '8/23/20', 'y': 16715},
   {'x': '8/24/20', 'y': 16821},
   {'x': '8/25/20', 'y': 16905},
   {'x': '8/26/20', 'y': 16962},
   {'x': '8/27/20', 'y': 17052}]},
 {'name': 'Bulgaria',
  'data': [{'x': '8/23/20', 'y': 15287},
   {'x': '8/24/20', 'y': 15386},
   {'x': '8/25/20', 'y': 15589},
   {'x': '8/26/20', 'y': 15751},
   {'x': '8/27/20', 'y': 15908}]},
 {'name': 'Paraguay',
  'data': [{'x': '8/23/20', 'y': 13233},
   {'x': '8/24/20', 'y': 13602},
   {'x': '8/25/20', 'y': 14228},
   {'x': '8/26/20', 'y': 14872},
   {'x': '8/27/20', 'y': 15290}]},
 {'name': 'Lebanon',
  'data': [{'x': '8/23/20', 'y': 12698},
   {'x': '8/24/20', 'y': 13155},
   {'x': '8/25/20', 'y': 13687},
   {'x': '8/26/20', 'y': 14248},
   {'x': '8/27/20', 'y': 14937}]},
 {'name': 'Madagascar',
  'data': [{'x': '8/23/20', 'y': 14327},
   {'x': '8/24/20', 'y': 14402},
   {'x': '8/25/20', 'y': 14475},
   {'x': '8/26/20', 'y': 14554},
   {'x': '8/27/20', 'y': 14592}]},
 {'name': 'North Macedonia',
  'data': [{'x': '8/23/20', 'y': 13595},
   {'x': '8/24/20', 'y': 13673},
   {'x': '8/25/20', 'y': 13799},
   {'x': '8/26/20', 'y': 13914},
   {'x': '8/27/20', 'y': 14004}]},
 {'name': 'Canada',
  'data': [{'x': '8/23/20', 'y': 126817},
   {'x': '8/24/20', 'y': 127594},
   {'x': '8/25/20', 'y': 127903},
   {'x': '8/26/20', 'y': 128380},
   {'x': '8/27/20', 'y': 128836}]},
 {'name': 'Senegal',
  'data': [{'x': '8/23/20', 'y': 12949},
   {'x': '8/24/20', 'y': 13013},
   {'x': '8/25/20', 'y': 13056},
   {'x': '8/26/20', 'y': 13186},
   {'x': '8/27/20', 'y': 13294}]},
 {'name': 'Sudan',
  'data': [{'x': '8/23/20', 'y': 12836},
   {'x': '8/24/20', 'y': 12903},
   {'x': '8/25/20', 'y': 12974},
   {'x': '8/26/20', 'y': 12974},
   {'x': '8/27/20', 'y': 13045}]},
 {'name': 'Kosovo',
  'data': [{'x': '8/23/20', 'y': 12448},
   {'x': '8/24/20', 'y': 12448},
   {'x': '8/25/20', 'y': 12683},
   {'x': '8/26/20', 'y': 12683},
   {'x': '8/27/20', 'y': 12683}]},
 {'name': 'Libya',
  'data': [{'x': '8/23/20', 'y': 10437},
   {'x': '8/24/20', 'y': 11009},
   {'x': '8/25/20', 'y': 11281},
   {'x': '8/26/20', 'y': 11834},
   {'x': '8/27/20', 'y': 12274}]},
 {'name': 'Zambia',
  'data': [{'x': '8/23/20', 'y': 11082},
   {'x': '8/24/20', 'y': 11148},
   {'x': '8/25/20', 'y': 11285},
   {'x': '8/26/20', 'y': 11376},
   {'x': '8/27/20', 'y': 11601}]},
 {'name': 'Norway',
  'data': [{'x': '8/23/20', 'y': 10323},
   {'x': '8/24/20', 'y': 10395},
   {'x': '8/25/20', 'y': 10454},
   {'x': '8/26/20', 'y': 10504},
   {'x': '8/27/20', 'y': 10542}]},
 {'name': 'Congo (Kinshasa)',
  'data': [{'x': '8/23/20', 'y': 9830},
   {'x': '8/24/20', 'y': 9842},
   {'x': '8/25/20', 'y': 9891},
   {'x': '8/26/20', 'y': 9912},
   {'x': '8/27/20', 'y': 9915}]},
 {'name': 'Greece',
  'data': [{'x': '8/23/20', 'y': 8664},
   {'x': '8/24/20', 'y': 8819},
   {'x': '8/25/20', 'y': 8987},
   {'x': '8/26/20', 'y': 9280},
   {'x': '8/27/20', 'y': 9531}]},
 {'name': 'Malaysia',
  'data': [{'x': '8/23/20', 'y': 9267},
   {'x': '8/24/20', 'y': 9274},
   {'x': '8/25/20', 'y': 9285},
   {'x': '8/26/20', 'y': 9291},
   {'x': '8/27/20', 'y': 9296}]},
 {'name': 'Guinea',
  'data': [{'x': '8/23/20', 'y': 8967},
   {'x': '8/24/20', 'y': 9076},
   {'x': '8/25/20', 'y': 9128},
   {'x': '8/26/20', 'y': 9167},
   {'x': '8/27/20', 'y': 9213}]},
 {'name': 'Croatia',
  'data': [{'x': '8/23/20', 'y': 8175},
   {'x': '8/24/20', 'y': 8311},
   {'x': '8/25/20', 'y': 8530},
   {'x': '8/26/20', 'y': 8888},
   {'x': '8/27/20', 'y': 9192}]},
 {'name': 'Albania',
  'data': [{'x': '8/23/20', 'y': 8427},
   {'x': '8/24/20', 'y': 8605},
   {'x': '8/25/20', 'y': 8759},
   {'x': '8/26/20', 'y': 8927},
   {'x': '8/27/20', 'y': 9083}]},
 {'name': 'France',
  'data': [{'x': '8/23/20', 'y': 280459},
   {'x': '8/24/20', 'y': 282414},
   {'x': '8/25/20', 'y': 285902},
   {'x': '8/26/20', 'y': 291374},
   {'x': '8/27/20', 'y': 297485}]},
 {'name': 'Gabon',
  'data': [{'x': '8/23/20', 'y': 8388},
   {'x': '8/24/20', 'y': 8409},
   {'x': '8/25/20', 'y': 8409},
   {'x': '8/26/20', 'y': 8468},
   {'x': '8/27/20', 'y': 8468}]},
 {'name': 'Tajikistan',
  'data': [{'x': '8/23/20', 'y': 8311},
   {'x': '8/24/20', 'y': 8346},
   {'x': '8/25/20', 'y': 8379},
   {'x': '8/26/20', 'y': 8413},
   {'x': '8/27/20', 'y': 8449}]},
 {'name': 'Haiti',
  'data': [{'x': '8/23/20', 'y': 8082},
   {'x': '8/24/20', 'y': 8110},
   {'x': '8/25/20', 'y': 8112},
   {'x': '8/26/20', 'y': 8122},
   {'x': '8/27/20', 'y': 8151}]},
 {'name': 'Finland',
  'data': [{'x': '8/23/20', 'y': 7920},
   {'x': '8/24/20', 'y': 7938},
   {'x': '8/25/20', 'y': 7981},
   {'x': '8/26/20', 'y': 8002},

## Country-wise

In [14]:
countryDataSpe=pd.DataFrame(confirmedGlobal[confirmedGlobal['Country/Region']=='China'][confirmedGlobal.columns[4:-1]].sum()).reset_index()
countryDataSpe.columns=['country','values']
countryDataSpe['lagVal']=countryDataSpe['values'].shift(1).fillna(0)
countryDataSpe['incrementVal']=countryDataSpe['values']-countryDataSpe['lagVal']
countryDataSpe['rollingMean']=countryDataSpe['incrementVal'].rolling(window=4).mean()
countryDataSpe=countryDataSpe.fillna(0)
datasetsForLine=[{'label':'Daily Cumulated Data','data':countryDataSpe['values'].values.tolist()},
                {'label':'Rolling Mean 4 days','data':countryDataSpe['rollingMean'].values.tolist()}]

In [15]:
countryDataSpe=pd.DataFrame(confirmedGlobal[confirmedGlobal['Country/Region']=='China'][confirmedGlobal.columns[4:-1]].sum()).reset_index()
countryDataSpe.columns=['country','values']

In [16]:
confirmedGlobal

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,NewContryCode
0,NaN,Afghanistan,33.939110,67.709953,0,0,0,0,0,0,...,37599,37599,37856,37894,37953,37999,38054,38070,38113,Afghanistan
1,NaN,Albania,41.153300,20.168300,0,0,0,0,0,0,...,7654,7812,7967,8119,8275,8427,8605,8759,8927,Albania
2,NaN,Algeria,28.033900,1.659600,0,0,0,0,0,0,...,39444,39847,40258,40667,41068,41460,41858,42228,42619,Algeria
3,NaN,Andorra,42.506300,1.521800,0,0,0,0,0,0,...,1005,1024,1024,1045,1045,1045,1060,1060,1098,Andorra
4,NaN,Angola,-11.202700,17.873900,0,0,0,0,0,0,...,1966,2015,2044,2068,2134,2171,2222,2283,2332,Angola
5,NaN,Antigua and Barbuda,17.060800,-61.796400,0,0,0,0,0,0,...,93,94,94,94,94,94,94,94,94,Antigua and Barbuda
6,NaN,Argentina,-38.416100,-63.616700,0,0,0,0,0,0,...,305966,312659,320884,329043,336802,342154,350867,359638,370188,Argentina
7,NaN,Armenia,40.069100,45.038200,0,0,0,0,0,0,...,41846,42056,42319,42477,42616,42792,42825,42936,43067,Armenia
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,113,113,113,113,113,113,113,113,113,AustraliaAustralian Capital Territory
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,3,4,...,3966,3971,3972,3981,3985,3988,3991,3997,4006,AustraliaNew South Wales
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,33,33,33,33,33,33,33,33,33,AustraliaNorthern Territory
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1092,1093,1094,1103,1105,1106,1106,1107,1110,AustraliaQueensland
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,462,462,462,462,462,463,463,463,463,AustraliaSouth Australia
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,AustraliaTasmania
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,1,1,...,17446,17683,17852,18029,18231,18330,18464,18608,18714,AustraliaVictoria
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,647,651,651,651,652,652,653,653,653,AustraliaWestern Australia
16,NaN,Austria,47.516200,14.550100,0,0,0,0,0,0,...,23829,24084,24431,24762,25062,25253,25495,25706,26033,Austria
17,NaN,Azerbaijan,40.143100,47.576900,0,0,0,0,0,0,...,34474,34620,34759,34921,35105,35274,35426,35559,35707,Azerbaijan
18,NaN,Bahamas,25.025885,-78.035889,0,0,0,0,0,0,...,1424,1531,1610,1703,1703,1765,1765,1765,1765,Bahamas
19,NaN,Bahrain,26.027500,50.550000,0,0,0,0,0,0,...,47581,47950,48303,48661,49038,49330,49719,50076,50393,Bahrain
20,NaN,Bangladesh,23.685000,90.356300,0,0,0,0,0,0,...,282344,285091,287959,290360,292625,294598,297083,299628,302147,Bangladesh
21,NaN,Barbados,13.193900,-59.543200,0,0,0,0,0,0,...,153,155,156,157,158,161,161,164,165,Barbados
22,NaN,Belarus,53.709800,27.953400,0,0,0,0,0,0,...,69673,69801,69950,70111,70285,70468,70645,70727,70974,Belarus
23,NaN,Belgium,50.833300,4.469936,0,0,0,0,0,0,...,78897,79479,80178,80894,81468,81936,82092,82447,83030,Belgium
24,NaN,Belize,17.189900,-88.497600,0,0,0,0,0,0,...,475,553,605,648,668,686,713,730,760,Belize
25,NaN,Benin,9.307700,2.315800,0,0,0,0,0,0,...,2063,2095,2095,2095,2115,2115,2115,2115,2145,Benin
26,NaN,Bhutan,27.514200,90.433600,0,0,0,0,0,0,...,147,147,153,154,155,155,156,173,173,Bhutan
27,NaN,Bolivia,-16.290200,-63.588700,0,0,0,0,0,0,...,103019,105050,106065,107435,108427,109149,110148,110999,112094,Bolivia
28,NaN,Bosnia and Herzegovina,43.915900,17.679100,0,0,0,0,0,0,...,16351,16691,17029,17396,17715,17715,18029,18326,18609,Bosnia and Herzegovina
29,NaN,Botswana,-22.328500,24.684900,0,0,0,0,0,0,...,1308,1308,1308,1308,1308,1308,1562,1562,1562,Botswana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236,NaN,Thailand,15.870032,100.992541,2,3,5,7,8,8,...,3382,3382,3389,3390,3390,3395,3402,3402,3404,Thailand
237,NaN,Timor-Leste,-8.874217,125.727539,0,0,0,0,0,0,...,25,25,25,25,26,26,26,26,26,Timor-Leste
238,NaN,Togo,8.619500,0.824800,0,0,0,0,0,0,...,1173,1190,1212,1239,1275,1277,1295,1309,1326,Togo
239,NaN,Trinidad and Tobago,10.691800,-61.222500,0,0,0,0,0,0,...,629,686,767,864,930,1007,1099,1252,1411,Trinidad and Tobago
240,NaN,Tunisia,33.886917,9.537499,0,0,0,0,0,0,...,2314,2427,2543,2607,2738,2818,2893,3069,3206,Tunisia
241,NaN,Turkey,38.963700,35.243300,0,0,0,0,0,0,...,251805,253108,254520,255723,257032,258249,259692,261194,262507,Turkey
242,NaN,US,40.000000,-100.000000,1,1,2,2,5,5,...,5483388,5529824,5573847,5622470,5667070,5701645,5739536,5777710,5821819,US
243,NaN,Uganda,1.373333,32.290275,0,0,0,0,0,0,...,1603,1656,1750,1848,2166,2263,2362,2426,2524,Uganda
244,NaN,Ukraine,48.379400,31.165600,0,0,0,0,0,0,...,96653,98658,100810,102948,105337,107379,109234,110949,112653,Ukraine
245,NaN,United Arab Emirates,23.424076,53.847818,0,0,0,0,0,0,...,64906,65341,65802,66193,66617,67007,67282,67621,68020,United Arab Emirates
246,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,United KingdomAnguilla
247,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,166,166,166,167,167,167,168,168,168,United KingdomBermuda
248,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,11,11,11,21,21,21,21,26,26,United KingdomBritish Virgin Islands
249,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,203,205,205,205,205,205,205,205,205,United KingdomCayman Islands
250,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,609,613,613,614,614,614,616,620,623,United KingdomChannel Islands
251,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,United KingdomFalkland Islands (Malvinas)
252,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,222,223,229,231,239,246,248,256,270,United KingdomGibraltar
253,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,336,336,336,336,336,336,336,336,336,United KingdomIsle of Man
254,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,United KingdomMontserrat
255,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,315,327,334,347,383,383,383,383,464,United KingdomTurks and Caicos Islands
256,NaN,United Kingdom,55.378100,-3.436000,0,0,0,0,0,0,...,320286,321098,322280,323313,324601,325642,326614,327798,328846,United Kingdom
257,NaN,Uruguay,-32.522800,-55.765800,0,0,0,0,0,0,...,1485,1493,1506,1516,1521,1527,1533,1536,1543,Uruguay
258,NaN,Uzbekistan,41.377491,64.585262,0,0,0,0,0,0,...,36352,37112,37547,38074,38532,38946,39348,39641,39964,Uzbekistan
259,NaN,Venezuela,6.423800,-66.589700,0,0,0,0,0,0,...,35697,36868,37567,38219,38957,39564,40338,41158,41965,Venezuela
260,NaN,Vietnam,14.058324,108.277199,0,2,2,2,2,2,...,989,994,1007,1009,1014,1016,1022,1029,1034,Vietnam
261,NaN,West Bank and Gaza,31.952200,35.233200,0,0,0,0,0,0,...,17306,17606,17989,18313,18476,18802,19213,19678,20155,West Bank and Gaza
262,NaN,Western Sahara,24.215500,-12.885800,0,0,0,0,0,0,...,10,10,10,10,10,10,10,10,10,Western Sahara
263,NaN,Yemen,15.552727,48.516388,0,0,0,0,0,0,...,1889,1892,1899,1906,1907,1911,1916,1924,1930,Yemen
264,NaN,Zambia,-13.133897,27.849332,0,0,0,0,0,0,...,9981,10218,10372,10627,10831,11082,11148,11285,11376,Zambia
265,NaN,Zimbabwe,-19.015438,29.154857,0,0,0,0,0,0,...,5378,5643,5745,5815,5893,5930,6070,6196,6251,Zimbabwe

## Prediction

In [91]:
recoverGlobal1=pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
recoverGlobal1['NewContryCode']=recoverGlobal1['Country/Region']+recoverGlobal1['Province/State'].fillna(' ')
recoverGlobal1.dropna( how='any', inplace=False)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,NewContryCode
8,Australian Capital Territory,Australia,-35.473500,149.012400,0,0,0,0,0,0,...,110,110,110,110,110,110,110,110,110,AustraliaAustralian Capital Territory
9,New South Wales,Australia,-33.868800,151.209300,0,0,0,0,0,0,...,2994,2995,2994,2994,2994,2994,2994,2994,2994,AustraliaNew South Wales
10,Northern Territory,Australia,-12.463400,130.845600,0,0,0,0,0,0,...,31,31,31,31,31,31,31,31,31,AustraliaNorthern Territory
11,Queensland,Australia,-27.469800,153.025100,0,0,0,0,0,0,...,1079,1081,1082,1082,1082,1082,1082,1083,1083,AustraliaQueensland
12,South Australia,Australia,-34.928500,138.600700,0,0,0,0,0,0,...,451,452,452,452,452,456,456,456,456,AustraliaSouth Australia
13,Tasmania,Australia,-42.882100,147.327200,0,0,0,0,0,0,...,216,216,216,216,216,216,216,216,216,AustraliaTasmania
14,Victoria,Australia,-37.813600,144.963100,0,0,0,0,0,0,...,9413,9729,12334,12940,13239,13708,14077,14572,14572,AustraliaVictoria
15,Western Australia,Australia,-31.950500,115.860500,0,0,0,0,0,0,...,633,633,633,633,634,634,635,636,637,AustraliaWestern Australia
43,Anhui,China,31.825700,117.226400,0,0,0,0,0,0,...,985,985,985,985,985,985,985,985,985,ChinaAnhui
44,Beijing,China,40.182400,116.414200,0,0,1,2,2,2,...,924,924,924,924,924,924,924,926,926,ChinaBeijing
45,Chongqing,China,30.057200,107.874000,0,0,0,0,0,0,...,577,577,577,577,577,577,577,577,577,ChinaChongqing
46,Fujian,China,26.078900,117.987400,0,0,0,0,0,0,...,365,365,365,365,365,365,365,365,366,ChinaFujian
47,Gansu,China,35.751800,104.286100,0,0,0,0,0,0,...,167,167,167,167,167,167,167,167,167,ChinaGansu
48,Guangdong,China,23.341700,113.424400,0,2,2,2,2,4,...,1689,1691,1695,1696,1701,1701,1702,1704,1706,ChinaGuangdong
49,Guangxi,China,23.829800,108.788100,0,0,0,0,0,0,...,253,253,253,253,253,253,253,253,253,ChinaGuangxi
50,Guizhou,China,26.815400,106.874800,0,0,0,0,0,0,...,145,145,145,145,145,145,145,145,145,ChinaGuizhou
51,Hainan,China,19.195900,109.745300,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,ChinaHainan
52,Hebei,China,37.895700,114.904200,0,0,0,0,0,0,...,343,343,343,343,343,343,343,343,343,ChinaHebei
53,Heilongjiang,China,47.862000,127.761500,0,0,0,0,0,0,...,934,934,934,934,934,934,934,934,934,ChinaHeilongjiang
54,Henan,China,33.882000,113.614000,0,0,0,0,0,0,...,1254,1254,1254,1254,1254,1254,1254,1254,1254,ChinaHenan
55,Hong Kong,China,22.300000,114.200000,0,0,0,0,0,0,...,3677,3779,3827,3900,3974,4018,4052,4108,4161,ChinaHong Kong
56,Hubei,China,30.975600,112.270700,28,28,31,32,42,45,...,63626,63626,63626,63626,63626,63626,63626,63626,63626,ChinaHubei
57,Hunan,China,27.610400,111.708800,0,0,0,0,0,0,...,1015,1015,1015,1015,1015,1015,1015,1015,1015,ChinaHunan
58,Inner Mongolia,China,44.093500,113.944800,0,0,0,0,0,0,...,256,256,256,257,257,257,257,257,257,ChinaInner Mongolia
59,Jiangsu,China,32.971100,119.455000,0,0,0,1,1,1,...,655,656,656,656,656,656,656,656,657,ChinaJiangsu
60,Jiangxi,China,27.614000,115.722100,0,0,0,0,0,2,...,931,931,931,931,931,931,931,931,932,ChinaJiangxi
61,Jilin,China,43.666100,126.192300,0,0,0,0,0,0,...,155,155,155,155,155,155,155,155,155,ChinaJilin
62,Liaoning,China,41.295600,122.608500,0,0,0,0,0,0,...,232,242,245,245,248,250,253,254,254,ChinaLiaoning
63,Macau,China,22.166700,113.550000,0,0,0,0,0,0,...,46,46,46,46,46,46,46,46,46,ChinaMacau
64,Ningxia,China,37.269200,106.165500,0,0,0,0,0,0,...,75,75,75,75,75,75,75,75,75,ChinaNingxia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Tibet,China,31.692700,88.092400,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,ChinaTibet
73,Xinjiang,China,41.112900,85.240100,0,0,0,0,0,0,...,569,597,625,672,701,716,739,775,792,ChinaXinjiang
74,Yunnan,China,24.974000,101.487000,0,0,0,0,0,0,...,189,189,189,189,189,189,189,189,189,ChinaYunnan
75,Zhejiang,China,29.183200,120.093400,0,0,1,1,1,1,...,1268,1268,1268,1268,1268,1268,1268,1268,1268,ChinaZhejiang
86,Faroe Islands,Denmark,61.892600,-6.911800,0,0,0,0,0,0,...,235,256,274,300,300,300,337,344,357,DenmarkFaroe Islands
87,Greenland,Denmark,71.706900,-42.604300,0,0,0,0,0,0,...,14,14,14,14,14,14,14,14,14,DenmarkGreenland
103,French Guiana,France,3.933900,-53.125800,0,0,0,0,0,0,...,8054,8112,8189,8251,8307,8307,8363,8399,8461,FranceFrench Guiana
104,French Polynesia,France,-17.679700,149.406800,0,0,0,0,0,0,...,68,68,68,68,68,68,68,148,202,FranceFrench Polynesia
105,Guadeloupe,France,16.265000,-61.551000,0,0,0,0,0,0,...,289,289,289,289,289,289,289,289,289,FranceGuadeloupe
106,Martinique,France,14.641500,-61.024200,0,0,0,0,0,0,...,98,98,98,98,98,98,98,98,98,FranceMartinique
107,Mayotte,France,-12.827500,45.166244,0,0,0,0,0,0,...,2964,2964,2964,2964,2964,2964,2964,2964,2964,FranceMayotte
108,New Caledonia,France,-20.904305,165.618042,0,0,0,0,0,0,...,22,22,22,22,22,22,23,23,23,FranceNew Caledonia
109,Reunion,France,-21.115100,55.536400,0,0,0,0,0,0,...,657,657,657,692,692,692,692,692,692,FranceReunion
110,Saint Barthelemy,France,17.900000,-62.833300,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,FranceSaint Barthelemy
111,Saint Pierre and Miquelon,France,46.885200,-56.315900,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,FranceSaint Pierre and Miquelon
112,St Martin,France,18.070800,-63.050100,0,0,0,0,0,0,...,49,49,49,52,52,52,52,52,52,FranceSt Martin
173,Aruba,Netherlands,12.521100,-69.968300,0,0,0,0,0,0,...,277,277,277,415,446,455,461,565,587,NetherlandsAruba
174,"Bonaire, Sint Eustatius and Saba",Netherlands,12.178400,-68.238500,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,"NetherlandsBonaire, Sint Eustatius and Saba"
175,Curacao,Netherlands,12.169600,-68.990000,0,0,0,0,0,0,...,31,31,31,32,33,33,34,34,34,NetherlandsCuracao
176,Sint Maarten,Netherlands,18.042500,-63.054800,0,0,0,0,0,0,...,107,133,146,146,147,147,147,147,179,NetherlandsSint Maarten
233,Anguilla,United Kingdom,18.220600,-63.068600,0,0,0,0,0,0,...,3,3,3,3,3,3,3,3,3,United KingdomAnguilla
234,Bermuda,United Kingdom,32.307800,-64.750500,0,0,0,0,0,0,...,147,147,147,147,149,149,150,151,151,United KingdomBermuda
235,British Virgin Islands,United Kingdom,18.420700,-64.640000,0,0,0,0,0,0,...,8,8,8,8,8,8,8,8,8,United KingdomBritish Virgin Islands
236,Cayman Islands,United Kingdom,19.313300,-81.254600,0,0,0,0,0,0,...,202,202,202,202,202,202,202,202,202,United KingdomCayman Islands
237,Channel Islands,United Kingdom,49.372300,-2.364400,0,0,0,0,0,0,...,545,545,545,545,545,545,545,545,545,United KingdomChannel Islands
238,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,0,0,0,0,0,0,...,13,13,13,13,13,13,13,13,13,United KingdomFalkland Islands (Malvinas)
239,Gibraltar,United Kingdom,36.140800,-5.353600,0,0,0,0,0,0,...,195,197,200,200,201,201,203,203,203,United KingdomGibraltar
240,Isle of Man,United Kingdom,54.236100,-4.548100,0,0,0,0,0,0,...,312,312,312,312,312,312,312,312,312,United KingdomIsle of Man
241,Montserrat,United Kingdom,16.742498,-62.187366,0,0,0,0,0,0,...,12,12,12,12,12,12,12,12,12,United KingdomMontserrat
242,Turks and Caicos Islands,United Kingdom,21.694000,-71.797900,0,0,0,0,0,0,...,56,56,102,102,102,102,102,102,102,United KingdomTurks and Caicos Islands

In [115]:
x=input("Enter a country: ")

Enter a country: Sint Maarten

In [116]:
x

'Sint Maarten'

In [117]:
final=recoverGlobal1[recoverGlobal1['Province/State']==x]
final

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,NewContryCode
176,Sint Maarten,Netherlands,18.0425,-63.0548,0,0,0,0,0,0,...,107,133,146,146,147,147,147,147,179,NetherlandsSint Maarten

In [118]:
data=[['1', int(final.iloc[:,-11])], ['2', int(final.iloc[:,-10])], ['3', int(final.iloc[:,-9])], ['4', int(final.iloc[:,-8])], ['5', int(final.iloc[:,-7])], ['6', int(final.iloc[:,-6])], ['7', int(final.iloc[:,-5])], ['8', int(final.iloc[:,-4])], ['9', int(final.iloc[:,-3])], ['10', int(final.iloc[:,-2])] ]

In [119]:
df = pd.DataFrame(data, columns = ['Day', 'Cases']) 
df

  Day  Cases
0   1    107
1   2    107
2   3    133
3   4    146
4   5    146
5   6    147
6   7    147
7   8    147
8   9    147
9  10    179

In [120]:
x =np.asarray(df['Day']).reshape(-1,1)
y =np.asarray(df['Cases']).reshape(-1,1)

In [121]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [122]:
model = LinearRegression()
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [123]:
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [124]:
predict_test = model.predict(x_test)

In [125]:
#(predict_test)

In [126]:
model.predict([[11]])

array([[167.98648649]])